### ISSUE TITLE
"Nice to have"-feature

### ISSUE THREAD

**Issue by thenrik** [justarrived/justarrived.github.io#144] opened 2016-12-09 15:51 UTC
![screenshot 2016-12-09 at 16 49 37 - display 2](https://cloud.githubusercontent.com/assets/22477699/21054863/921ae02e-be2f-11e6-9556-ba03dd700bec.png)

Remove hyperlink from 1. and only have it on the word "Registrera"
- looks more pleasing to the eye :)

http://justarrived.se/decemberutmaningen/

**Comment by buren** [comment] 2016-12-10 11:52
@thenrik thanks we actually want it to pop-out a bit even though its pretties without it. We want to make it really clear that there is an action to be taken on that page and not only content.

Thank you for the feedback 👍 

Closing this since this is by design.

**Closed as completed by buren** 2016-12-10 11:52 UTC
