### ISSUE TITLE
Top heading bar and headline needs to be centered on top, "For companies" page (Arabic)

### ISSUE THREAD

**Issue by xEPIx** [justarrived/justarrived.github.io#91] opened 2016-10-22 10:39 UTC
Just found this little error while browsing http://justarrived.se/ar/company/
image below:

![1](https://cloud.githubusercontent.com/assets/16858071/19618798/98a50e8e-9854-11e6-9322-7d208e20366a.jpg)

**Comment by buren** [comment] 2016-10-30 08:54
@xEPIx is this 👇 the desired result?

<img width="1296" alt="screen shot 2016-10-30 at 09 54 11" src="https://cloud.githubusercontent.com/assets/922411/19835439/d8925d66-9e86-11e6-8dcc-f375435b151f.png">

**Comment by xEPIx** [comment] 2016-11-06 22:13
It should be Top centered, if thats possiple

**Comment by buren** [comment] 2016-11-07 00:04
@tikkat my suggested fix ☝️ was never merged in code. Just posted here as a screenshot.

**Comment by tikkat** [comment] 2016-11-07 14:52
@buren This is not a bug/problem and should therefore be closed, I talked with Ahmed about it yesterday :) forgot to tell you in this issue before I closed it

**Closed as completed** 2016-11-07 14:52 UTC
Labels: right-to-left

**Comment by buren** [comment] 2016-11-07 17:48
Ah, cool 👍 Awesome @tikkat and @xEPIx
